version: '3.9'

services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - 15692:15692
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
