version: '3.9'

services:
  postgres:
    image: postgres:12
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  authorization:
    image: python:3.7.14-alpine3.16
    ports: 
      - 8081:8081
    volumes:
      - ./webserver:/app
    command: python -m http.server 8081 --directory app
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 15692:15692
      - 15672:15672
      - 5672:5672
    volumes:
      - type: bind
        source: ./enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
